services:
  - type: web
    name: hair-salon-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d23mkoqdbo4c738dhvj0-a.frankfurt-postgres.render.com:5432/hair_salon_db_xoyx?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: hair_salon_db_xoyx_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: assqoe1gvA6SzAPrhB6Q6SDOgDVKXGMe
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
